server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user_home}/Desktop/dev/native-file-repo
#        git:
#          uri: file:///D:/dev/spring_study/springcloud/ecommerce.yml # local git